<div style="background-image: linear-gradient(to bottom,#f4f4f4,white);">
    <div class="row" style="background-image: linear-gradient(to bottom, #ac2925,#d9534f); height: 20px; box-shadow: 3px 3px 3px #999"></div>
    <div style="color:#fff ;padding-left: 5px; padding-right: 5px; float:right; width: 400px; height: 100px; background-image: linear-gradient(to bottom,#d9534f,#f8605c); border-radius: 0px 0px 10px 10px; margin-top: -10px; margin-right: 10px; box-shadow: 3px 3px 3px #999">
        <div class="col-sm-12">
            <div style="opacity: 0.7;"><b><span class="glyphicon glyphicon-lock"></span> ACESSO AO SEU AMBIENTE</b></div>
        </div>
        <div class="col-sm-6">
            <label class="control-label small"> Nome de Usuário</label>
            <input class="form-control" type="text" name="username" id="username"/>
        </div>
        <div class="col-sm-4">
            <label class="control-label small"> Senha</label>
            <input class="form-control" type="password" name="username" id="username"/>
        </div>
        <div class="col-sm-2" style="text-align: right;margin-top: 25px">
            <button class="btn btn-warning btn-sm">OK</button>
        </div>
    </div>
    <div class="row" style="margin-left: 10px">
        <img src="<?= $this->img("mg.png") ?>"/>
    </div>
</div>