<div class="navbar navbar-inverse" role="navigation" style="margin-top: -5px; border-radius: 0px">
    <div class="container">
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-list-alt"></span> Empresa<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->link('/nota/emissao'); ?>"><span class="glyphicon glyphicon-file"></span> Missão</a></li>
                        <li><a href="<?= $this->link('/nota/consulta'); ?>"><span class="glyphicon glyphicon-file"></span> Visão</a></li>
                        <li><a href="<?= $this->link('/nota/cancelar'); ?>"><span class="glyphicon glyphicon-file"></span> Objetivo</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-list-alt"></span> Servico<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?= $this->link('/rps/cadastro'); ?>"><span class="glyphicon glyphicon-file"></span> Contabilidade</a></li>
                        <li><a href="<?= $this->link('/rps/consulta'); ?>"><span class="glyphicon glyphicon-file"></span> Fiscal</a></li>
                        <li><a href="<?= $this->link('/rps/cancelar'); ?>"><span class="glyphicon glyphicon-file"></span> Pessoal</a></li>
                        <li><a href="<?= $this->link('/rps/cancelar'); ?>"><span class="glyphicon glyphicon-file"></span> Empresarial</a></li>
                    </ul>
                </li>
                <li><a href="<?= $this->link('/security/logout') ?>">Sair</a></li>
            </ul>
        </div>
    </div>
</div>

